### ISSUE TITLE
Кнопки в ListBox нажимаются, если зажата левая кнопка мыши

### ISSUE THREAD

**Issue by linkarvane** [Laun4er/TheRestLauncher#1]
Надо бы в коде сделать так, чтобы кнопки нажимались только тогда, когда отпускаешь левую кнопку мыши. Также желательно отключить нажатие кнопок от правой мыши

Вроде здесь можно что-то взять https://stackoverflow.com/questions/7589142/why-does-the-wpf-listbox-change-selection-on-mouse-button-down-rather-than-butto

**Comment by Laun4er** [comment]
https://metanit.com/sharp/wpf/6.3.php
Вот здесь есть все события мыши
