### ISSUE TITLE
Updater.exe

### ISSUE THREAD

**Issue by Laun4er** [Laun4er/TheRestLauncher#2]
https://stackoverflow.com/questions/24386905/how-to-download-file-from-google-drive-in-wpf-installed-application

Я наткнулся на статью, где подробно описывается загрузка с гугл диска. Я хочу с утра попробовать сделать сначала интерфейс апдейтера, который будет соответствовать цветам в лаунчере, сделать прогресс бар загрузки (наполнение бокала), и приписать функцию автозапуска TheRestLauncher.exe. Звучит довольно просто, однако я хочу разобраться, что означает та или иная функция. Впринципе все, я выпущу отдельный репозиторий, а также, если все будет работать, то я все запаковываю в установщик, и выпускаю ОБТ(пока будем без профилей, стандартный ник я указал Steve). Я еще думаю попробовать самим создать базу данных для профилей, скинов и тд, завтра также распрошу проггера сайта

**Comment by Laun4er** [comment]
Кстати, будет еще сложная задача у меня - это проверка всех файлов майна через апдейтер(может быть долговато, но зато мы будем знать, что все четко)

**Comment by linkarvane** [comment]
капец

**Comment by Laun4er** [comment]
Чувствую себя диким проггером, но зато будет все четко и круто(да и будем честны, это наш первый серьёзный проект, который будет завязан на всем)

**Comment by izumrudik01** [comment]
мейби просто можно закинуть файлы майна на гугл диск и он будет их сверять с теми, что на компе? такое возможно вообще?

**Comment by Laun4er** [comment]
> мейби просто можно закинуть файлы майна на гугл диск и он будет их сверять с теми, что на компе? такое возможно вообще?
> 
> 

Дело в том, что я пока не нашел библиотек, которые будут сверять файлы на гугл драйве. Еще хочу подметить, что если файл весит >25МБ, то будет вызываться окно, что не удалось проверить файл на наличие вирусов

**Comment by izumrudik01** [comment]
хм

**Comment by izumrudik01** [comment]
https://github.com/ravibpatel/AutoUpdater.NET в английском не бом бом, просто что-то нашел по запросу в гугле, чекните, то ли это

**Comment by izumrudik01** [comment]
https://www.youtube.com/watch?v=Bz85Iu1_ajI еще нашел эту херню

**Comment by Laun4er** [comment]
https://learn.microsoft.com/ru-ru/visualstudio/deployment/how-clickonce-performs-application-updates?view=vs-2022
Можно будет попробовать ClickOnce вопользоваться
