### ISSUE TITLE
Кнопка "моды", "новости", "настройки" и тд

### ISSUE THREAD

**Issue by izumrudik01** [Laun4er/TheRestLauncher#3]
Поговорил с другом, который кодил на с++, сказал, что, что бы сделать кнопки "настройки" "моды" и тп, можно сделать так, что бы при нажатии кнопки закрывалось основное окно и открывалось окно с новостями или что-то типо того, это костыль ( цитата)

**Comment by izumrudik01** [comment]
а если делать не костылем, то вкладка новости, будет просто накладываться поверх главной менюхи, это как я понял

**Comment by Laun4er** [comment]
Так ведь можно задать подключение 2-х библиотек в разных xaml, что может просто показывать некую информацию. Либо, находить способ, чтоб можно было "вытягивать" информацию

**Comment by linkarvane** [comment]
> а если делать не костылем, то вкладка новости, будет просто накладываться поверх главной менюхи, это как я понял

я примерно так и хотел, чтобы менялость только то, что справа

**Comment by Laun4er** [comment]
Короче, я понял, как делать так:
1. Нужно задать Click_button всем этим кнопкам. После в Private Void указать _NavigationFrame Page.xaml();
2. После всего этого указанного, необходимо задать анимацию, как это всё будет выглядеть
3. Ну и сегодня в стороннем приложении попробую, потом в случае удачи я выпущу обнову лаунчера

**Comment by linkarvane** [comment]
Реализовано в 5e5d5fa1841d8627ca5f8fac576b269e5ceb3e54 и 6debd0d46f4fd93efc01be9cf6622e51a844e138
